Feature/add remaining yaml files
OpenInsurance-Brasil/areadesenvolvedor pull request #4
Opened 2021-11-09 15:53 UTC by MatheusDev-1

### Alterações

Adicionado mais arquivos .YAML com sua formatação seguindo o linting do **spectral**.
 - Automóvel
 - Pessoas
 - Previdência
 - Vida e Previdência
 - Admin Metrics

2021-11-09 21:26 UTC, wesleyfantinel requested changes

2021-11-09 21:26 UTC, wesleyfantinel commented on swagger/open_admin_metrics.yaml
> +    url: 'https://http://novosite.susep.gov.br'
Pode só por favor deixar o mesmo dos demais swaggers? Obrigado!

2021-11-09 21:26 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +  /life-pension/{cnpjNumber}:
@MatheusDev-1 `/life-pension/{cnpjNumber}` não seria apenas `/life-pensions`? Este `{cnpjNumber} `seria necessário, já que o retorno apresenta uma lista de `Companies`? 

Seguindo a referência da API de produtos e serviços do open banking, exemplo: https://github.com/OpenBanking-Brasil/areadesenvolvedor/blob/master/documentation/source/swagger/swagger_products_services_apis.yaml#L18

2021-11-09 21:26 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +    url: 'https://http://novosite.susep.gov.br'
Aqui ficaria `https://openinsurance.susep.gov.br` também?

2021-11-09 21:26 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +  - url: 'https://api.organizacao.com.br/open-insurance/products-services/v1'
Só para entendermos, esta é a URL base que você está sugerindo `products-services/v1`.

Se olharmos para as informações da regra 3.1.1, ficaria algo assim no endpoint final?
`https://api.organizacao.com.br/open-insurance/products-services/v1/life-pension/{cnpjNumber} `

2021-11-11 14:53 UTC, MatheusDev-1 commented on swagger/open_life_welfare.yaml
> +  /life-pension/{cnpjNumber}:
Tive que colocar desta forma porque o linter não estava deixando passar.

Na linha 546 o cnpjNumber está definido como 'in: path', então acredito que deva ficar desta maneira.

2021-11-11 16:03 UTC, wesleyfantinel requested changes

2021-11-11 16:03 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +  /life-pension/{cnpjNumber}:
Eu não pude localizar nos swaggers do OpenBanking a referência do número do CNPJ nos paths. 

Novamente olhando para o `ResponseLifePensionList`, é retornado uma array de `LifePensionCompany` que por sua vez contém vários CNPJs. Acho que podemos seguir sem o cnpj no path por conta disso. Oq vc acha?

2021-11-11 16:14 UTC, MatheusDev-1 commented on swagger/open_life_welfare.yaml
> +  /life-pension/{cnpjNumber}:
É uma boa, também acho que podemos seguir sem. Removi dos arquivos aqui.

2021-11-11 16:56 UTC, wesleyfantinel requested changes

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +  /life-pension:
Excelente! Agora creio que visando uma melhor semântica, estas rotas ficariam melhor definidas no plural, assim como o OpenBanking também faz. Pois já que o endpoint em questão retorna uma lista com vários itens, nada mais natural do que "solicitar" para a API no plural. Faz sentido?

Aqui por exemplo ficaria algo como `life-pensions`. Acha uma boa?

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_life_welfare.yaml
> +      operationId: "getLifePension"
No operationId, eu também deixaria no plural.

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_people.yaml
> +  /person:
Que tal a rota se chamar `/persons`, no plural aqui também?

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_welfare.yaml
> +  /pension-plan:
Acredito que `/pension-plans` ficaria perfeito, concorda?

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_residence.yaml
> +  /home-insurance/commercializationArea/{commercializationArea}:
Aqui "home" na tradução literal está muito ligado apenas à "casa". Este produto apesar de ser residencial, pode englobar outros tipos de imóveis, como apartamentos e escritórios:

![Screen Shot 2021-11-11 at 13 52 50](https://user-images.githubusercontent.com/3750220/141337326-7a600a45-4e3c-41cb-8228-5ef8840cd422.png)

Acredito que um nome mais apropriado para essa seria o qual você já colocou no nome do arquivo, "residence".
Sendo assim, o rota poderia começar em "/residences" ou até mesmo "/residentials". Oq vc acha disso?

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_residence.yaml
> +  /home-insurance/commercializationArea/{commercializationArea}:
Também não entendi o `commercializationArea/{commercializationArea}`poderia explicar por favor, para deixar documentado?

2021-11-11 16:56 UTC, wesleyfantinel commented on swagger/open_vehicle.yaml
> +  /auto-insurance/{commercializationArea}/{fipeCode}/{year}:
Sobre o `{commercializationArea}/{fipeCode}/{year}` poderia explicar por favor, para deixar documentado?

2021-11-14 21:16 UTC, merged